// <auto-generated />
using HSU.PTWeb.AnhPH.BookStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HSU.PTWeb.AnhPH.BookStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315143000_AddCityWardMasterTables")]
    partial class AddCityWardMasterTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
